ServiceHost = "0.0.0.0"
ServicePort = 8080

https_address = ":8443"
https_cert_file = "certs/server.crt"
https_key_file = "certs/server.key"

endpoint = "localhost:9000"
access_key = "root"
secret_key = "rootroot"
use_ssl = false
bucket = "ripimages"

jwt_secret_key = "etokabachok"
jwt_expires_in = "24h"
jwt_issuer = "repback-app"

redis_dial_timeout = "10s"
redis_read_timeout = "10s"